fieldLayouts:
  9b7bb58e-1b6e-4b3f-b745-cb144eb0b259:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c313a9ac-87b1-46de-938f-1e6f5cf7f1af
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e34bc4ec-e913-4f31-9644-c7acd3ee209d
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
