columnSuffix: oeqxninj
contentColumnType: string(255)
fieldGroup: 5ee6e8a8-5e6c-41ac-8d9e-de9aac106267 # Common
handle: feedbackiframe
instructions: null
name: feedbackIframe
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
